"""empty message

Revision ID: 043a6c8e7e5d
Revises: e0c8e87ecff6
Create Date: 2023-11-05 23:37:14.605588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043a6c8e7e5d'
down_revision: Union[str, None] = 'e0c8e87ecff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
