"""unique

Revision ID: d155b72dbe7b
Revises: 
Create Date: 2023-11-04 20:19:05.402497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d155b72dbe7b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_fund_name", "FUND", ["fund_name"])
    op.create_unique_constraint(
        "uq_fund_manager_email", "FUND_MANAGER", ["fund_manager_email"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_fund_name", "FUND_MANAGER", type_="unique")
    op.drop_constraint("uq_fund_manager_email", "FUND", type_="unique")
    # ### end Alembic commands ###
