"""empty message

Revision ID: e0c8e87ecff6
Revises: f967930f8102
Create Date: 2023-11-05 23:27:09.167240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c8e87ecff6'
down_revision: Union[str, None] = 'f967930f8102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FUND_MANAGER',
    sa.Column('fund_manager_id', sa.Integer(), nullable=False),
    sa.Column('fund_manager_name', sa.String(), nullable=False),
    sa.Column('fund_manager_email', sa.String(), nullable=False),
    sa.Column('date_created_on', sa.Date(), nullable=False),
    sa.Column('date_updated_on', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('fund_manager_id'),
    sa.UniqueConstraint('fund_manager_email')
    )
    op.create_table('FUND',
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=False),
    sa.Column('fund_manager_id', sa.Integer(), nullable=False),
    sa.Column('fund_description', sa.String(), nullable=False),
    sa.Column('fund_date_of_creation', sa.Date(), nullable=False),
    sa.Column('fund_date_of_update', sa.Date(), nullable=False),
    sa.Column('fund_performance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fund_manager_id'], ['FUND_MANAGER.fund_manager_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fund_id'),
    sa.UniqueConstraint('fund_name')
    )
    op.create_table('FUND_NAV_DATA',
    sa.Column('fund_nav_data_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('fund_nav_data', sa.Float(), nullable=False),
    sa.Column('fund_nav_data_date_of_creation', sa.DateTime(), nullable=False),
    sa.Column('fund_nav_data_date_of_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['FUND.fund_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fund_nav_data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FUND_NAV_DATA')
    op.drop_table('FUND')
    op.drop_table('FUND_MANAGER')
    # ### end Alembic commands ###
