"""add table

Revision ID: ea8d8a16db7a
Revises: d155b72dbe7b
Create Date: 2023-11-04 22:51:24.410420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8d8a16db7a'
down_revision: Union[str, None] = 'd155b72dbe7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FUND_NET_ASSET_VALUE',
    sa.Column('fund_nav_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('fund_nav', sa.Float(), nullable=False),
    sa.Column('fund_nav_date_of_creation', sa.DateTime(), nullable=False),
    sa.Column('fund_nav_date_of_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['FUND.fund_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fund_nav_id')
    )
    op.drop_column('FUND', 'fund_net_asset_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FUND', sa.Column('fund_net_asset_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('FUND_NET_ASSET_VALUE')
    # ### end Alembic commands ###
