"""add new table

Revision ID: f967930f8102
Revises: ea8d8a16db7a
Create Date: 2023-11-05 11:51:05.579097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f967930f8102'
down_revision: Union[str, None] = 'ea8d8a16db7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FUND_NAV_DATA',
    sa.Column('fund_nav_data_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('fund_nav_data', sa.Float(), nullable=False),
    sa.Column('fund_nav_data_date_of_creation', sa.DateTime(), nullable=False),
    sa.Column('fund_nav_data_date_of_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['FUND.fund_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fund_nav_data_id')
    )
    op.drop_table('FUND_NET_ASSET_VALUE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FUND_NET_ASSET_VALUE',
    sa.Column('fund_nav_id', sa.INTEGER(), server_default=sa.text('nextval(\'"FUND_NET_ASSET_VALUE_fund_nav_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fund_nav', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fund_nav_date_of_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fund_nav_date_of_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['FUND.fund_id'], name='FUND_NET_ASSET_VALUE_fund_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fund_nav_id', name='FUND_NET_ASSET_VALUE_pkey')
    )
    op.drop_table('FUND_NAV_DATA')
    # ### end Alembic commands ###
